INSERT INTO managedb.auth_permission (name, content_type_id, codename) VALUES ('Can add log entry', 1, 'add_logentry');
INSERT INTO managedb.auth_permission (name, content_type_id, codename) VALUES ('Can change log entry', 1, 'change_logentry');
INSERT INTO managedb.auth_permission (name, content_type_id, codename) VALUES ('Can delete log entry', 1, 'delete_logentry');
INSERT INTO managedb.auth_permission (name, content_type_id, codename) VALUES ('Can add permission', 2, 'add_permission');
INSERT INTO managedb.auth_permission (name, content_type_id, codename) VALUES ('Can change permission', 2, 'change_permission');
INSERT INTO managedb.auth_permission (name, content_type_id, codename) VALUES ('Can delete permission', 2, 'delete_permission');
INSERT INTO managedb.auth_permission (name, content_type_id, codename) VALUES ('Can add user', 3, 'add_user');
INSERT INTO managedb.auth_permission (name, content_type_id, codename) VALUES ('Can change user', 3, 'change_user');
INSERT INTO managedb.auth_permission (name, content_type_id, codename) VALUES ('Can delete user', 3, 'delete_user');
INSERT INTO managedb.auth_permission (name, content_type_id, codename) VALUES ('Can add group', 4, 'add_group');
INSERT INTO managedb.auth_permission (name, content_type_id, codename) VALUES ('Can change group', 4, 'change_group');
INSERT INTO managedb.auth_permission (name, content_type_id, codename) VALUES ('Can delete group', 4, 'delete_group');
INSERT INTO managedb.auth_permission (name, content_type_id, codename) VALUES ('Can add content type', 5, 'add_contenttype');
INSERT INTO managedb.auth_permission (name, content_type_id, codename) VALUES ('Can change content type', 5, 'change_contenttype');
INSERT INTO managedb.auth_permission (name, content_type_id, codename) VALUES ('Can delete content type', 5, 'delete_contenttype');
INSERT INTO managedb.auth_permission (name, content_type_id, codename) VALUES ('Can add session', 6, 'add_session');
INSERT INTO managedb.auth_permission (name, content_type_id, codename) VALUES ('Can change session', 6, 'change_session');
INSERT INTO managedb.auth_permission (name, content_type_id, codename) VALUES ('Can delete session', 6, 'delete_session');
INSERT INTO managedb.auth_permission (name, content_type_id, codename) VALUES ('Can add dataflow', 8, 'add_dataflow');
INSERT INTO managedb.auth_permission (name, content_type_id, codename) VALUES ('Can change dataflow', 8, 'change_dataflow');
INSERT INTO managedb.auth_permission (name, content_type_id, codename) VALUES ('Can delete dataflow', 8, 'delete_dataflow');
INSERT INTO managedb.auth_permission (name, content_type_id, codename) VALUES ('Can add package', 9, 'add_package');
INSERT INTO managedb.auth_permission (name, content_type_id, codename) VALUES ('Can change package', 9, 'change_package');
INSERT INTO managedb.auth_permission (name, content_type_id, codename) VALUES ('Can delete package', 9, 'delete_package');
INSERT INTO managedb.auth_permission (name, content_type_id, codename) VALUES ('Can add sms', 10, 'add_sms');
INSERT INTO managedb.auth_permission (name, content_type_id, codename) VALUES ('Can change sms', 10, 'change_sms');
INSERT INTO managedb.auth_permission (name, content_type_id, codename) VALUES ('Can delete sms', 10, 'delete_sms');
INSERT INTO managedb.auth_permission (name, content_type_id, codename) VALUES ('Can add standard', 11, 'add_standard');
INSERT INTO managedb.auth_permission (name, content_type_id, codename) VALUES ('Can change standard', 11, 'change_standard');
INSERT INTO managedb.auth_permission (name, content_type_id, codename) VALUES ('Can delete standard', 11, 'delete_standard');
INSERT INTO managedb.auth_permission (name, content_type_id, codename) VALUES ('Can add traffic', 12, 'add_traffic');
INSERT INTO managedb.auth_permission (name, content_type_id, codename) VALUES ('Can change traffic', 12, 'change_traffic');
INSERT INTO managedb.auth_permission (name, content_type_id, codename) VALUES ('Can delete traffic', 12, 'delete_traffic');
INSERT INTO managedb.auth_permission (name, content_type_id, codename) VALUES ('Can add user', 13, 'add_user');
INSERT INTO managedb.auth_permission (name, content_type_id, codename) VALUES ('Can change user', 13, 'change_user');
INSERT INTO managedb.auth_permission (name, content_type_id, codename) VALUES ('Can delete user', 13, 'delete_user');
INSERT INTO managedb.auth_permission (name, content_type_id, codename) VALUES ('Can add account', 15, 'add_account');
INSERT INTO managedb.auth_permission (name, content_type_id, codename) VALUES ('Can change account', 15, 'change_account');
INSERT INTO managedb.auth_permission (name, content_type_id, codename) VALUES ('Can delete account', 15, 'delete_account');
INSERT INTO managedb.auth_permission (name, content_type_id, codename) VALUES ('Can add number', 16, 'add_number');
INSERT INTO managedb.auth_permission (name, content_type_id, codename) VALUES ('Can change number', 16, 'change_number');
INSERT INTO managedb.auth_permission (name, content_type_id, codename) VALUES ('Can delete number', 16, 'delete_number');