# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-05 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('accountNumber', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('packNumber', models.CharField(max_length=50)),
                ('accountFee', models.CharField(max_length=50)),
                ('localBalance', models.IntegerField()),
                ('remoteBalance', models.IntegerField()),
                ('dataBalance', models.IntegerField()),
                ('balance', models.FloatField(max_length=20)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='dataflow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userNumber', models.CharField(max_length=20)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('dataflow', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='package',
            fields=[
                ('packNumber', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='sms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('senderNumber', models.CharField(max_length=20)),
                ('receiverNumber', models.CharField(max_length=20)),
                ('sendTime', models.DateTimeField()),
                ('receiveTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='standard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('localFee', models.CharField(max_length=20)),
                ('smsFee', models.CharField(max_length=20)),
                ('dataFee', models.CharField(max_length=20)),
                ('remoteFee', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='traffic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('callerNumber', models.CharField(max_length=20)),
                ('receiverNumber', models.CharField(max_length=20)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('callType', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('personalID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('userType', models.CharField(default='user', max_length=20)),
                ('accountNumber', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='personalID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FK_personalID', to='managesys.user'),
        ),
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FK_username', to='managesys.user'),
        ),
    ]
