# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-23 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managesys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='personalID',
        ),
    ]
