# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managesys', '0003_auto_20161005_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataflow',
            name='Fee',
            field=models.FloatField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sms',
            name='Fee',
            field=models.FloatField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traffic',
            name='Fee',
            field=models.FloatField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
