# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managesys', '0003_auto_20160923_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15)),
            ],
        ),
    ]
