# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 08:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managesys', '0004_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='number',
            old_name='number',
            new_name='phoneNumber',
        ),
    ]
