# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managesys', '0005_auto_20161006_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='smsBalance',
            field=models.IntegerField(default=0),
        ),
    ]
