# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 10:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managesys', '0008_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='accountType',
            new_name='packNumber',
        ),
    ]
